#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require 'wide_bot'
require 'pry'

module WideBot
  jra_fetcher = JRACalendarFetcher.new
  jra_html = jra_fetcher.fetch(Date.new(2022, 8, 7))

  jra_parser = JRACalendarHTMLParser.new
  race_ids = jra_parser.parse(jra_html)

  race_id = race_ids.sample.main_id
  # race_id = "202209021211"
  # race_id YYYYCCTTDDJRR
  # YYYY: 開催年
  # CC:   競馬場コード(lib/wide_bot/database/race_course_id_table.rb参照)
  # TT:   第TT回開催
  # DD:   DD日目
  # RR:   第RRレース

  nk_fetcher = NetkeibaFetcher.new
  nk_html = nk_fetcher.fetch(race_id)

  nk_parser = NetkeibaHTMLParser.new
  race_info = nk_parser.parse(nk_html)

  keiba_master = KeibaMaster.new
  good_running_horses = keiba_master.predict_race(race_info)

  formatter = TweetFormatter.new
  tweet_text = formatter.format(good_running_horses, race_info)

  client = TwitterBot.new
  # client.say(tweet_text)
end
