#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require 'wide_bot'
require 'pry'

module WideBot
  url = "https://race.netkeiba.com/race/shutuba.html?race_id=202209021211"

  fetcher = NetkeibaFetcher.new
  html = fetcher.fetch(url)

  parser = NetkeibaHTMLParser.new
  race_info = parser.parse(html)

  keiba_master = KeibaMaster.new
  good_running_horses = keiba_master.predict_race(race_info)

  formatter = TweetFormatter.new
  tweet_text = formatter.format(good_running_horses, race_info)

  client = TwitterBot.new
  client.say(tweet_text)
end
